lucancountrygardens/about/urls.py
from django.conf.urls import url, patterns, include
from about import views

urlpatterns = patterns("",
    url(
        regex=r"^$",
        view=views.AboutListView.as_view(),
        name='about_list',
    ),
    url(
        regex=r"^(?P<slug>[-\w]+)/$",
        view=views.AboutDetailView.as_view(),
        name="about_detail",
    ),
)

lucancountrygardens/gallery/urls.py
from django.conf.urls import url, patterns, include
from gallery import views

urlpatterns = patterns("",
    url(
        regex=r"^$",
        view=views.GalleryListView.as_view(),
        name='gallery_list',
    ),
    url(
        regex=r"^(?P<slug>[-\w]+)/$",
        view=views.GalleryDetailView.as_view(),
        name="gallery_detail",
    ),
)

lucancountrygardens/lucancountrygardens/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from .sitemap import ProductSitemap, CategorySitemap, GallerySitemap, AboutSitemap
from .views import RobotPageView, HumanPageView, GooglePageView, HomePageView
admin.autodiscover()

sitemaps = {
    'product': ProductSitemap,
    'category': CategorySitemap,
    'gallery': GallerySitemap,
    'about': AboutSitemap,
}

urlpatterns = patterns('',
    url(
        regex=r"^$",
        view=HomePageView.as_view(),
        name="home_page",
    ),
    url(
        regex=r"^robots\.txt$",
        view=RobotPageView.as_view(),
        name="site_robots",
    ),
    url(
        regex=r"^humans\.txt$",
        view=HumanPageView.as_view(),
        name="site_humans",
    ),
    url(
        regex=r"^google25e8e23e2bfc7d2c\.html$",
        view=GooglePageView.as_view(),
        name="google_webmasters",
    ),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('haystack.urls')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery', app_name='gallery')),
    url(r'^about/', include('about.urls', namespace='about', app_name='about')),
    url(r'^contact/', include('contact.urls', namespace='contact', app_name='contact')),
    url(r'^', include('product.urls', namespace='product', app_name='product')),
)

lucancountrygardens/gallery/models.py
from django.db import models
from django.core.urlresolvers import reverse
from sorl.thumbnail import ImageField

class Gallery(models.Model):
    name = models.CharField( max_length=255, unique=True )
    slug = models.SlugField( max_length=255, unique=True )
    description = models.TextField( blank=True )
    meta_description = models.CharField( max_length=255, blank=True )
    meta_keywords = models.CharField( max_length=255, blank=True )
    is_active = models.BooleanField( default=True )

    class Meta:
        app_label = 'gallery'
        ordering = ['name']
        verbose_name_plural = "galleries"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('gallery:gallery_detail', kwargs={'slug':self.slug})
        

class GalleryImage(models.Model):
    gallery = models.ForeignKey('Gallery')
    image = models.ImageField(upload_to="gallery/", blank=True, null=True)
    caption = models.CharField( max_length=255, blank=True)
    sort = models.IntegerField( default=0 )

    class Meta:
        app_label = 'gallery'
        ordering = ['sort']
    
    def __str__(self):
        return self.caption

lucancountrygardens/gallery/views.py
from django.views import generic
from gallery.models import Gallery

class GalleryDetailView(generic.DetailView):
    model = Gallery

class GalleryListView(generic.ListView):
    queryset = Gallery.objects.filter(is_active=True)

lucancountrygardens/templates/gallery/gallery_detail.html
{% extends "base.html" %}
{% load product_tags thumbnail %}

{% block title %}{{ gallery }}{% endblock %}
{% block meta_description %}{{ gallery.meta_description }}{% endblock %}
{% block meta_keywords %}{{ gallery.meta_description }}{% endblock %}

{% block extra_head %}
  <meta name="robots" content="index,follow">
{% endblock %}

{% block content %}
<div class="container">

<div class="page-header">

<ol class="breadcrumb">
  <li><a href="{% url 'gallery:gallery_list' %}">Galleries</a></li>
  <li>{{ gallery }}</li>
</ol>  

<p>{{gallery.description|safe}}</p>
</div>


{% if gallery.galleryimage_set.all %}
  {% for row in gallery.galleryimage_set.all|partition_horizontal:"4" %}
    <div class="row">
      {% for item in row %}
        <div class="col-md-3">
           <div class="panel panel-default">
              <div class="panel-body">
                <h4 class="text-center">{{item}}</h4>
                {% thumbnail item.image "1000" as big %}
                  {% thumbnail item.image "250" crop="center" as small %}
                    <a href="{{ big.url}}" title="look ma!">
                      <img class="img-responsive" src="{{ small.url }}" title="{{ item }}" alt="thumbnail">
                    </a>
                  {% endthumbnail %}
                {% endthumbnail %}
              </div>
          </div>
        </div>
     {% endfor %}
    </div>
    {% endfor %}
{% endif %}
</div>

{% endblock %}

lucancountrygardens/templates/gallery/gallery_list.html
{% extends "base.html" %}
{% load product_tags thumbnail %}

{% block title %}Gallery{% endblock %}

{% block extra_head %}
<meta name="robots" content="index,follow">
{% endblock %}

{% block content %}

<div class="container">

<div class="page-header">

<h1>Photo Galleries</h1>
<p>Not only do we enjoy growing plants, we also enjoy taking pictures of them and putting them on display. 
That is what these pages are for. As time goes on we'll keep adding more galleries. 
If you see any pictures of which you would like to have the HD version, just stop on by and we'll be happy to provide it for you.
</p>
</div>

{% if object_list %}  
  {% for row in object_list|partition_horizontal:"4" %}
    <div class="row">
      {% for item in row %}
        <div class="col-md-3">
           <div class="panel panel-default">
            <a href="{{ item.get_absolute_url }}" title="{{ item.name }}" target="_self">
              <div class="panel-body">
                <h4 class="text-center">{{item.name}}</h4>
{% thumbnail item.galleryimage_set.all|first "1000" as im %}
    <img class="img-responsive" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
{% endthumbnail %}
              </div>
            </a>
          </div>
        </div>
     {% endfor %}
    </div>
    {% endfor %}
{% endif %}
</div>
{% endblock %}