lucancountrygardens/about/urls.py
from django.conf.urls import url, patterns, include
from about import views

urlpatterns = patterns("",
    url(
        regex=r"^$",
        view=views.AboutListView.as_view(),
        name='about_list',
    ),
    url(
        regex=r"^(?P<slug>[-\w]+)/$",
        view=views.AboutDetailView.as_view(),
        name="about_detail",
    ),
)

lucancountrygardens/contact/urls.py
from django.conf.urls import url, patterns, include
from contact import views

urlpatterns = patterns("",
    url(
        regex=r"^$",
        view=views.ContactView.as_view(),
        name='contact_page',
    ),
)

lucancountrygardens/gallery/urls.py
from django.conf.urls import url, patterns, include
from gallery import views

urlpatterns = patterns("",
    url(
        regex=r"^$",
        view=views.GalleryListView.as_view(),
        name='gallery_list',
    ),
    url(
        regex=r"^(?P<slug>[-\w]+)/$",
        view=views.GalleryDetailView.as_view(),
        name="gallery_detail",
    ),
)

lucancountrygardens/lucancountrygardens/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from .sitemap import ProductSitemap, CategorySitemap, GallerySitemap, AboutSitemap
from .views import RobotPageView, HumanPageView, GooglePageView, HomePageView
admin.autodiscover()

sitemaps = {
    'product': ProductSitemap,
    'category': CategorySitemap,
    'gallery': GallerySitemap,
    'about': AboutSitemap,
}

urlpatterns = patterns('',
    url(
        regex=r"^$",
        view=HomePageView.as_view(),
        name="home_page",
    ),
    url(
        regex=r"^robots\.txt$",
        view=RobotPageView.as_view(),
        name="site_robots",
    ),
    url(
        regex=r"^humans\.txt$",
        view=HumanPageView.as_view(),
        name="site_humans",
    ),
    url(
        regex=r"^google25e8e23e2bfc7d2c\.html$",
        view=GooglePageView.as_view(),
        name="google_webmasters",
    ),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('haystack.urls')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery', app_name='gallery')),
    url(r'^about/', include('about.urls', namespace='about', app_name='about')),
    url(r'^contact/', include('contact.urls', namespace='contact', app_name='contact')),
    url(r'^', include('product.urls', namespace='product', app_name='product')),
)

lucancountrygardens/product/urls.py
from django.conf.urls import url, patterns
from product.views import CategoryListView, CategoryDetailView, ProductDetailView

urlpatterns = patterns('',
    url(
        r"^categories/$", 
        CategoryListView.as_view(), 
        name="category_list"
    ),
    url(
        r"^product/(?P<slug>[-\w]+)/$",
        ProductDetailView.as_view(), 
        name="product_detail"
    ),
    url(
        r"^(?P<parent_slugs>([-\w]+/)*)?(?P<slug>[-\w]+)/$",
        CategoryDetailView.as_view(),
        name="category_detail"
    ),
)

lucancountrygardens/product/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Category(models.Model):
    parent = models.ForeignKey('self', null=True, blank=True )
    name = models.CharField( max_length=255, unique=True )   
    slug = models.SlugField( max_length=255, unique=True )  
    description = models.TextField( blank=True)
    sort = models.IntegerField( unique=True, max_length=2, default=0 )  
    meta_description = models.CharField( max_length=255, blank=True )
    meta_keywords = models.CharField( max_length=255, blank=True )     
    is_active = models.BooleanField( default=True )    
    image = models.ImageField( upload_to="images/", blank=True, null=True )

    class Meta:
        app_label = 'product'
        ordering = ['sort']
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def _recurse_for_parents(self, cat_obj):
        p_list = []
        if cat_obj.parent_id:
            p = cat_obj.parent
            p_list.append(p)
            if p != self:
                more = self._recurse_for_parents(p)
                p_list.extend(more)
        if cat_obj == self and p_list:
            p_list.reverse()
        return p_list

    def get_absolute_url(self):
        parents = self._recurse_for_parents(self)
        slug_list = [cat.slug for cat in parents]
        if slug_list:
            slug_list = "/".join(slug_list) + "/"
        else:
            slug_list = ""
        return reverse('product:category_detail',
            kwargs={'parent_slugs' : slug_list, 'slug' : self.slug})


class Product(models.Model):
    name = models.CharField( max_length=255 )
    slug = models.SlugField( max_length=255, unique=True )  
    category = models.ForeignKey('Category', null=True, blank=True )
    meta_description = models.CharField( max_length=255, blank=True )
    meta_keywords = models.CharField( max_length=255, blank=True )                
    is_active = models.BooleanField( default=True )    
    is_featured = models.BooleanField( default=False )    
    price = models.DecimalField( max_digits=8, decimal_places=2 )
    description = models.TextField( blank=True)

    class Meta:
        app_label = 'product'
        ordering = ['name']
                
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:product_detail', kwargs={'slug':self.slug})


class ProductImage(models.Model):
    product = models.ForeignKey('Product')
    image = models.ImageField( upload_to="images/", blank=True, null=True)
    caption = models.CharField( max_length=255, blank=True)
    sort = models.IntegerField( default=0 )

    class Meta:
        app_label = 'product'
        ordering = ['sort']
    
    def __str__(self):
            return self.caption
  

lucancountrygardens/templates/base.html
{% load staticfiles thumbnail %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Joost Vandorp" >

    <title>{% block title %}{% endblock %}| Lucan Country Gardens</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'dist/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'dist/css/sticky-footer-navbar.css' %}" rel="stylesheet">
    <link href="{% static 'dist/css/carousel.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    {% block extra_head %}
    {% endblock extra_head %}
  </head>

  <body>
    <!-- Wrap all page content here -->
    <div id="wrap">
      <div class="navbar-wrapper">
        <div class="container">
          <div class="row hidden-xs">
            <div class="col-md-4 col-sm-4 col-xs-4">
              <a href="{% url 'home_page' %}">
                {% thumbnail "https://www.lucancountrygardens.ca/media/cache/bd/d5/bdd5babd4236e7b4c33aeba852c5efe7.png" "250" format="PNG" as im %}
                  <img class="img-responsive" src="{{ im.url }}" alt="Lucan Country Gardens" />
                {% endthumbnail %}
              </a>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
              <div class="page-header">
                <h2 class="text-right">(519) 227-1716</h2>
              </div>  
            </div>
          </div><!-- ./row -->
        </div><!-- ./container -->
        
        <div class="navbar navbar-inverse" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand visible-xs" href="{% url 'home_page' %}">Lucan Country Gardens</a>
            </div>

            <div class="collapse navbar-collapse">

              <form class="navbar-form navbar-right" role="search" method="get" action="/search/">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search" name="q" id="q">
                </div>
                <button type="submit" class="btn btn-default" value="search">Submit</button>
              </form>

              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'gallery:gallery_list' %}">Galleries</a></li>
                <li><a href="{% url 'about:about_list' %}">About</a></li>
                <li><a href="{% url 'product:category_list' %}">Products</a></li>
                <li><a href="{% url 'contact:contact_page' %}">Contact</a></li>
              </ul>

            </div><!--/.nav-collapse -->
          </div><!-- /.container -->
        </div><!-- /.navbar -->
      </div><!-- /.navbar-wrapper -->
      <!-- Begin page content -->
      {% block content %}
      {% endblock content %}
    </div>

    <div id="footer">
      <div class="container">
        <p class="text-muted text-center"> Designed by: <a href="http://vandorjw.me">Joost van Dorp</a>
         ||
<!--[if lte IE 8]><span style="filter: FlipH; -ms-filter: "FlipH"; display: inline-block;"><![endif]-->
<span style="-moz-transform: scaleX(-1); -o-transform: scaleX(-1); -webkit-transform: scaleX(-1); transform: scaleX(-1); display: inline-block;">
&copy;
</span>
<!--[if lte IE 8]></span><![endif]-->
Lucan Country Gardens</p>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'docs-assets/js/holder.js' %}"></script>

  </body>
</html>

lucancountrygardens/templates/home_page.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% load product_tags %}
{% block extra_head %}
<meta name="robots" content="index,follow">
{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-12">

    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->

      <ol class="carousel-indicators">
      {% for slide in jumbotron %}
        <li data-target="#myCarousel" data-slide-to="{{forloop.counter0}}"></li>
      {% endfor %}
      </ol>

      <div class="carousel-inner">
      {% for item in jumbotron %}
        <div class="item {% if forloop.first %}active{% endif %}">
          <img class="img-responsive" src="media/{{item.image}}" alt="{{item.caption}}" />
          <div class="container">
            <div class="carousel-caption">
              <h1>{{item.headline}}</h1>
              <p>{{item.caption}}</p>
            </div>
          </div>
        </div>
      {% endfor %}
        
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->

    </div><!-- /.col-md-8 offset-2 -->
  </div><!-- /.row -->

  <div class="row">
    <h4>Welcome to Lucan Country Gardens</h4>
    <p>
We are located on Highway 4, between the city of London, and the town of Exeter. 
See our <a href="{% url 'contact:contact_page' %}">contact page</a> for more details and a 

<a href="https://www.google.ca/maps/preview#!q=lucan+country+gardens&data=!4m15!2m14!1m13!1s0x882edef386d6577d%3A0xbaa37592b8adb0a7!3m8!1m3!1d2401!2d-81.4529907!3d43.2077849!3m2!1i1366!2i634!4f13.1!4m2!3d43.207785!4d-81.452991">map</a> 
on how to find us. 
We carry a large variety of producs for all your garden needs. Here are some quick links to get you started:</p>
  </div>

  {% if root_categories %}
  <div class="row">
    <h4>Categories</h4>
  </div>

    {% for row in root_categories|partition_horizontal:"4" %}
      <div class="row">
        {% for item in row %}
          <div class="col-md-3 col-sm-3">

           <div class="panel panel-default">
            <a href="{{ item.get_absolute_url }}" title="{{ item.name }}" target="_self">
              <div class="panel-body">
                <h4 class="text-center">{{item.name}}</h4>
                <img class="img-responsive hidden-xs" src="/media/{{item.image}}" alt="category-image" />
              </div>
            </a> 
          </div>

          </div>
        {% endfor %}
      </div>
    {% endfor %}
  {% endif %} 


  {% if featured_products %}
  <div class="row">
    <h4>Featured Products</h4>
  </div>
    {% for row in featured_products|partition_horizontal:"4" %}
      <div class="row">
        {% for item in row %}
          <div class="col-md-3 col-sm-3">

           <div class="panel panel-default">
            <a href="{{ item.get_absolute_url }}" title="{{ item.name }}" target="_self">
              <div class="panel-body">
                <h4 class="text-center">{{item.name}}</h4>
                {% with item.productimage_set.all|first as im %}
                <img class="img-responsive hidden-xs" src="/media/{{im.image}}" alt="category-image" />
                {% endwith %}
              </div>
            </a> 
          </div>

          </div>
        {% endfor %}
      </div>
    {% endfor %}
  {% endif %} 

</div><!-- End Container -->

{% endblock content %}